apiVersion: v1
kind: Pod
metadata:
  name: myspc-pod
  labels:
    app: spc
spec:
  containers:
    - name: my-spc-container
      image: "984912521466.dkr.ecr.ap-south-1.amazonaws.com/spc/image:latest"
      ports:
        - containerPort: 8080

