name: GitHub Actions

on: 
  push: 
    branches: 
      - main

jobs: 
  build:
      name: my-spc
      runs-on: self-hosted
      steps:
        - name: git checkout
          uses: actions/checkout@v4
        - name: Build java with maven
          run: mvn package

        - name: sonar scanner
          env: 
            SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
            SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
          run: mvn clean verify sonar:sonar

        